In [2]:
import pandas as pd
#Load the dataset
df = pd.read_csv("Chocolate Sales (2).csv")
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

## Lets Understand the data much more

In [3]:
df.shape

(3282, 6)

In [4]:
df.dtypes

Sales Person     object
Country          object
Product          object
Date             object
Amount           object
Boxes Shipped     int64
dtype: object

##### Note :
- Column called Date is not in the date format ie.Date datatype
- Amount ( Object with $ and , -> Numerical datatype )

In [3]:
# Convert Date column
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

# Clean Amount column
df['Amount'] = (
    df['Amount']
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [6]:
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [7]:
df.dtypes

Sales Person             object
Country                  object
Product                  object
Date             datetime64[ns]
Amount                  float64
Boxes Shipped             int64
dtype: object

In [8]:
#Check Missing Values
df.isnull().sum()

Sales Person     0
Country          0
Product          0
Date             0
Amount           0
Boxes Shipped    0
dtype: int64

## Feature Engineering

In [4]:
#Creating essential features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek

In [13]:
df.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped,Year,Month,Day,DayOfWeek
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180,2022,1,4,1
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94,2022,8,1,0
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91,2022,7,7,3
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342,2022,4,27,2
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184,2022,2,24,3

#### Why this matters
- Sales often vary by month
- Weekdays vs weekends matter
- Seasonal patterns

#### Analysis with Sales Person (EDA)

In [14]:
# Total sales by sales person
sales_by_person = (
    df.groupby('Sales Person')['Amount']
    .sum()
    .sort_values(ascending=False)
)

print(sales_by_person.head(10))

Sales Person
Ches Bonnell           1022599.96
Oby Sorrel             1017204.12
Madelene Upcott        1010028.72
Kelci Walkden          1002929.10
Brien Boise             997326.48
Van Tuxwell             974425.09
Dennison Crosswaite     931849.57
Beverie Moffet          892421.37
Kaine Padly             849062.76
Marney O'Breen          836427.63
Name: Amount, dtype: float64

#### Further some Analysis according to the date feature

In [6]:
# Monthly sales trend
monthly_sales = df.groupby(['Year', 'Month'])['Amount'].sum()
print(monthly_sales)

# Day-of-week sales
df['DayName'] = df['Date'].dt.day_name()
dow_sales = df.groupby('DayName')['Amount'].sum().sort_values(ascending=False)
print(dow_sales)

Year  Month
2022  1         896105.00
      2         699377.00
      3         749483.00
      4         674051.00
      5         752892.00
      6         865144.00
      7         803425.00
      8         743148.00
2023  1         958985.77
      2         749617.46
      3         807494.33
      4         727743.72
      5         811951.78
      6         932625.17
      7         861856.66
      8         793103.07
2024  1        1013621.82
      2         783102.44
      3         847791.96
      4         760132.50
      5         850906.79
      6         976162.77
      7         902250.63
      8         830599.99
Name: Amount, dtype: float64
DayName
Thursday     4052553.28
Friday       3750049.65
Wednesday    3043032.95
Tuesday      2775047.84
Saturday     2545771.28
Monday       2322538.78
Sunday       1302578.08
Name: Amount, dtype: float64

#### Prepare data for model

In [7]:
# Drop columns not used directly in ML
df_model = df.drop(columns=['Sales Person', 'Date', 'DayName'])

X = df_model.drop('Amount', axis=1)
y = df_model['Amount']

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

categorical_cols = ['Country', 'Product']
numeric_cols = ['Boxes Shipped', 'Year', 'Month', 'Day', 'DayOfWeek']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
        ('num', 'passthrough', numeric_cols)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
#Linear Regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

lr_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

lr_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Country', 'Product']),
                                                 ('num', 'passthrough',
                                                  ['Boxes Shipped', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek'])])),
                ('model', LinearRegression())])

In [12]:
#Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Country', 'Product']),
                                                 ('num', 'passthrough',
                                                  ['Boxes Shipped', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [14]:
from sklearn.ensemble import GradientBoostingRegressor

gb_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', GradientBoostingRegressor(random_state=42))
])

gb_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Country', 'Product']),
                                                 ('num', 'passthrough',
                                                  ['Boxes Shipped', 'Year',
                                                   'Month', 'Day',
                                                   'DayOfWeek'])])),
                ('model', GradientBoostingRegressor(random_state=42))])

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
def evaluate_model(model, X_test, y_test):
    preds = model.predict(X_test)
    return {
        "MAE": mean_absolute_error(y_test, preds),
        "RMSE": np.sqrt(mean_squared_error(y_test, preds)),
        "R2": r2_score(y_test, preds)
    }

results = pd.DataFrame({
    "Linear Regression": evaluate_model(lr_model, X_test, y_test),
    "Random Forest": evaluate_model(rf_model, X_test, y_test),
    "Gradient Boosting": evaluate_model(gb_model, X_test, y_test)
})
res_df = pd.DataFrame(results)
res_df

      Linear Regression  Random Forest  Gradient Boosting
MAE         3420.492017    2065.714199        3187.817266
RMSE        4110.007648    2645.038276        3909.923324
R2            -0.003803       0.584255           0.091552

#### Lets do a hyperparameter tuning to see the changes

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

In [18]:
#Tuning of Random Forest
rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(random_state=42))
])

In [19]:
param_grid = {
    'model__n_estimators': [100, 200, 300],
    'model__max_depth': [None, 10, 20, 30],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 4]
}

In [20]:
grid_search = GridSearchCV(
    rf_pipeline,
    param_grid,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Country',
                                                                          'Product']),
                                                                        ('num',
                                                                         'passthrough',
                                                                         ['Boxes '
                                                                          'Shipped',
                                                                          'Year',
                                                                          'Month',
                                                                          'Day',
                                                                          'DayOfWeek'])])),
                                       ('model',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [None, 10, 20, 30],
                         'model__min_samples_leaf': [1, 2, 4],
                         'model__min_samples_split': [2, 5, 10],
                         'model__n_estimators': [100, 200, 300]},
             scoring='neg_root_mean_squared_error', verbose=2)

In [21]:
print("Best Parameters:")
print(grid_search.best_params_)

Best Parameters:
{'model__max_depth': None, 'model__min_samples_leaf': 1, 'model__min_samples_split': 2, 'model__n_estimators': 100}

In [32]:
#Evaluate the tuning model
best_rf_model = grid_search.best_estimator_

tuned_rf_results = evaluate_model(best_rf_model, X_test, y_test)
tuned_rf_results

{'MAE': 2065.714199391172,
 'RMSE': np.float64(2645.0382761356977),
 'R2': 0.5842546934032491}

In [33]:
comparison = pd.DataFrame({
    "Before Tuning": results['Random Forest'],
    "After Tuning": tuned_rf_results
})

comparison

      Before Tuning  After Tuning
MAE     2065.714199   2065.714199
RMSE    2645.038276   2645.038276
R2         0.584255      0.584255

##### Here it shows already our base rf model is a optimal one.

#### Lets do a tuning for Gradient Boosting

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor

gb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', GradientBoostingRegressor(random_state=42))
])

In [25]:
gb_param_grid = {
    'model__n_estimators': [100, 200, 300],
    'model__learning_rate': [0.05, 0.1, 0.2],
    'model__max_depth': [2, 3, 4],
    'model__subsample': [0.8, 1.0]
}

In [26]:
from sklearn.model_selection import GridSearchCV

gb_grid_search = GridSearchCV(
    gb_pipeline,
    gb_param_grid,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    verbose=2
)

gb_grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['Country',
                                                                          'Product']),
                                                                        ('num',
                                                                         'passthrough',
                                                                         ['Boxes '
                                                                          'Shipped',
                                                                          'Year',
                                                                          'Month',
                                                                          'Day',
                                                                          'DayOfWeek'])])),
                                       ('model',
                                        GradientBoostingRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1, 0.2],
                         'model__max_depth': [2, 3, 4],
                         'model__n_estimators': [100, 200, 300],
                         'model__subsample': [0.8, 1.0]},
             scoring='neg_root_mean_squared_error', verbose=2)

In [27]:
print("Best GB Parameters:")
print(gb_grid_search.best_params_)

Best GB Parameters:
{'model__learning_rate': 0.2, 'model__max_depth': 4, 'model__n_estimators': 300, 'model__subsample': 0.8}

In [28]:
best_gb_model = gb_grid_search.best_estimator_

tuned_gb_results = evaluate_model(best_gb_model, X_test, y_test)
tuned_gb_results

{'MAE': 2160.6594332224468,
 'RMSE': np.float64(2808.992711742465),
 'R2': 0.5311168157371084}

In [29]:
gb_comparison = pd.DataFrame({
    "Before Tuning": results['Gradient Boosting'],
    "After Tuning": tuned_gb_results
})

gb_comparison

      Before Tuning  After Tuning
MAE     3187.817266   2160.659433
RMSE    3909.923324   2808.992712
R2         0.091552      0.531117

#### comparing the tuned model rf vs gb

In [38]:
final_comparison = pd.DataFrame({
    "Base Random Forest": results['Random Forest'],
    "Base Gradient Boosting Forest": results['Gradient Boosting'],
    "Tuned Random Forest": tuned_rf_results,
    "Tuned Gradient Boosting": tuned_gb_results
})

final_comparison

,Base Random Forest,Base Gradient Boosting Forest,Tuned Random Forest,Tuned Gradient Boosting
MAE,2065.714199,3187.817266,2065.714199,2160.659433
RMSE,2645.038276,3909.923324,2645.038276,2808.992712
R2,0.584255,0.091552,0.584255,0.531117

#### 🏆 FINAL OPTIMUM MODEL IS -> Random Forest Regressor (Tuned / Default)
**Even after proper GB tuning:**
- RF still has lower error
- RF explains more variance
- RF is more stable,
**Random Forest is the best model for this dataset.**

# THE END